[FIX] add correct errors in the main and change the order in the coding-style run commands

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -24,18 +24,6 @@ jobs:
       - name: Display banana report
         run: cat /temp/coding-style-reports.log
 
-      - name: Report banana result
-        run: |
-          NB_ERROR=$(cat coding-style-reports.log | wc -l)
-          if [ $NB_ERROR -gt 0 ]; then
-            ERRORS=$(cat coding-style-reports.log);
-            echo "Banana found $NB_ERROR error(s)"
-            echo "$ERRORS"
-            exit 1
-          fi
-          echo "Everything is good ! Keep on coding !"
-          exit 0
-
       - name: Create annotation for coding-style errors
         run: |
           input=coding-style-reports.log
@@ -48,6 +36,19 @@ jobs:
             echo ${fields[4]}
           done < $input
           echo "::title=${fields[2]},error file=${fields[0]},line=${fields[1]}::${fields[3]}"
+          
+      - name: Report banana result
+        run: |
+          NB_ERROR=$(cat coding-style-reports.log | wc -l)
+          if [ $NB_ERROR -gt 0 ]; then
+            ERRORS=$(cat coding-style-reports.log);
+            echo "Banana found $NB_ERROR error(s)"
+            echo "$ERRORS"
+            exit 1
+          fi
+          echo "Everything is good ! Keep on coding !"
+          exit 0
+
 
   check_program_compilation:
     runs-on: ubuntu-latest
